add support for pluggable weather backends

diff --git a/wethr b/wethr
--- a/wethr
+++ b/wethr
@@ -1,12 +1,7 @@
 #!/bin/sh
 
-version="0.3.0"
+version="0.4.0"
 weather_expiration_secs=3600
-
-default_params="units=si&lang=en&extend=hourly&exclude=currently,daily,alerts,flags"
-params=${WETHR_PARAMS:-"$default_params"}
-api_base="https://api.darksky.net/forecast"
-endpoint="${api_base}/${DARKSKY_API_KEY}/${COORDS}?$params"
 
 die() {
   echo "$@" >&2
@@ -25,22 +20,80 @@ next_color() {
 
 data_source() {
   case $1 in
-    a) ds="apparentTemperature";;
-    B) ds="windBearing";;
-    c) ds="cloudCover*100";;
-    d) ds="dewPoint";;
-    G) ds="windGust";;
-    h) ds="humidity*100";;
-    I) ds="precipIntensity";;
-    o) ds="ozone";;
-    p) ds="precipProbability*100";;
-    r) ds="pressure";;
-    t) ds="temperature";;
-    u) ds="uvIndex";;
-    v) ds="visibility";;
-    w) ds="windSpeed";;
-    *) ds="";;
+    clouds | c) ds="clouds";;
+    dew_point | dp) ds="dew_point";;
+    feels_like | f) ds="feels_like";;
+    humidity | h) ds="humidity";;
+    ozone | o) ds="ozone";;
+    precip_amnt | pa) ds="precip_amnt";;
+    precip_prob | pp) ds="precip_prob";;
+    pressure | pr) ds="pressure";;
+    temp | t) ds="temp";;
+    uv | u) ds="uv";;
+    visibility | v) ds="visibility";;
+    wind_dir | wd) ds="wind_dir";;
+    wind_gust | wg) ds="wind_gust";;
+    wind_speed | ws) ds="wind_speed";;
+    *) die "invalid data source '$1'";;
   esac
+}
+
+set_backend_() {
+  case $1 in
+    darksky)
+      [ -z $DARKSKY_API_KEY ] && die "please set DARKSKY_API_KEY"
+      local params="units=si&lang=en&extend=hourly&exclude=currently,daily,alerts,flags"
+      local api_base="https://api.darksky.net/forecast"
+      endpoint="${api_base}/${DARKSKY_API_KEY}/${COORDS}?$params"
+      jq_extract_date=".hourly.data[0].time"
+      jq_normalize='[.hourly.data[] | {
+        "feels_like": .apparentTemperature,
+        "clouds": (.cloudCover*100),
+        "dew_point": .dewPoint,
+        "humidity": (.humidity*100),
+        "ozone": .ozone,
+        "precip_prob": (.precipProbability*100),
+        "precip_amnt": .precipIntensity,
+        "pressure": .pressure,
+        "temp": .temperature,
+        "uv": .uvIndex,
+        "visibility": .visibility,
+        "wind_dir": .windBearing,
+        "wind_gust": .windGust,
+        "wind_speed": .windSpeed
+      }]'
+      ;;
+    openweathermap)
+      [ -z $OWM_API_KEY ] && die "please set OWM_API_KEY"
+      local params="lat=${COORDS%%,*}&lon=${COORDS##*,}&APPID=${OWM_API_KEY}&units=metric"
+      local api_base="https://api.openweathermap.org/data/2.5/forecast"
+      endpoint="$api_base?$params"
+      jq_extract_date=".list[0].dt"
+      jq_normalize='[.list[] | {
+        "feels_like": .main.temp,
+        "clouds": .clouds.all,
+        "dew_point": 0,
+        "humidity": .main.humidity,
+        "ozone": 0,
+        "precip_prob": 0,
+        "precip_amnt": .rain."3h",
+        "pressure": .main.pressure,
+        "temp": .main.temp,
+        "uv": 0,
+        "visibility": 0,
+        "wind_dir": .wind.deg,
+        "wind_gust": 0,
+        "wind_speed": .wind.speed
+      } | [., ., .]] | flatten'
+      ;;
+    *)
+      die "invalid backend '$1'"
+      ;;
+  esac
+}
+
+download_() {
+  curl --compressed -sS "$@"
 }
 
 fetch_weather() {
@@ -56,10 +109,9 @@ fetch_weather() {
   if [ $force_fetch ] || [ ! -f "$data_dir/src" ] \
     || [ $((ctime - last_fetch)) -gt $weather_expiration_secs ]
   then
-    [ -z $DARKSKY_API_KEY ] && die "please set DARKSKY_API_KEY"
-
-    curl --compressed -sS "$endpoint" > "$data_dir/src" || \
+    download_ "$endpoint" > "$data_dir/src" || \
       if [ -f "$data_dir/src" ]; then
+        echo "failed to fetch new data"
         return;
       else
         die "couldn't download data"
@@ -68,7 +120,7 @@ fetch_weather() {
     [ -d "$data_dir/derived" ] && rm -r "$data_dir/derived"
     mkdir -p "$data_dir/derived"
 
-    initial_date=$(jq '.hourly.data[0].time' "$data_dir/src")
+    initial_date=$(jq "$jq_extract_date" "$data_dir/src")
 
     [ -z $initial_date ] && die "failed to extract data"
 
@@ -79,6 +131,9 @@ last_fetch=$ctime
 human_date='$(date)'
 hour_offset=$hour_offset
 EOF
+
+    jq "$jq_normalize" "$data_dir/src" > "$data_dir/norm" \
+      || die "failed to normalize data"
   fi
 
   source "$data_dir/metadata"
@@ -90,43 +145,45 @@ USAGE:
   wethr [options]
 
 OPTIONS
+  -b darksky|openweathermap - select backend to use
   -d <DATA> - add data to the output
   -f - force redownloading of cached data
-  -p <OPTS> - pass along OPTS to plot
+  -p <OPTS> - pass along OPTS to plot(1)
 
 DATA:
-\e[1;4;36ma\e[0mpparentTemperature
-wind\e[1;4;36mB\e[0mearing
-\e[1;4;36mc\e[0mloudCover*100
-\e[1;4;36md\e[0mewPoint
-wind\e[1;4;36mG\e[0must
-\e[1;4;36mh\e[0mumidity*100
-precip\e[1;4;36mI\e[0mntensity
-\e[1;4;36mo\e[0mzone
-\e[1;4;36mp\e[0mrecipProbability*100
-p\e[1;4;36mr\e[0messure
-\e[1;4;36mt\e[0memperature
-\e[1;4;36mu\e[0mvIndex
-\e[1;4;36mv\e[0misibility
-\e[1;4;36mw\e[0mindSpeed
+clouds, c
+dew_point, dp
+feels_like, f
+humidity, h
+ozone, o
+precip_amnt, pa
+precip_prob, pp
+pressure, pr
+temp, t
+uv, u
+visibility, v
+wind_dir, wd
+wind_gust, wg
+wind_speed, ws
 
 ENVIRONMENT
   COORDS - lattitude,longitude
     coordinates to fetch the weather for
-  DARKSKY_API_KEY - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-    your api key
 "
 }
 
+backend=darksky
 force_fetch=""
 data=""
 plot_args=""
 data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/wethr2"
-echo $data_dir
 mkdir -p "$data_dir" || die "failed to create data directory"
 
-while getopts "hp:d:f" opt; do
+while getopts "hp:d:fb:" opt; do
   case $opt in
+    b)
+      backend="$OPTARG"
+      ;;
     p)
       plot_args="$plot_args -${OPTARG##-}"
       ;;
@@ -134,9 +191,7 @@ while getopts "hp:d:f" opt; do
       data_source "$OPTARG"
       data="$ds $data"
       ;;
-    f)
-      force_fetch=1
-      ;;
+    f) force_fetch=1;;
     h)
       print_usage
       exit
@@ -148,9 +203,10 @@ while getopts "hp:d:f" opt; do
   esac
 done
 
+set_backend_ "$backend"
 fetch_weather
 
-data=${data:-temperature}
+data=${data:-temp}
 
 echo "last fetched: $human_date"
 plot_data=""
@@ -160,9 +216,9 @@ for d in $data; do
 
   printf "\e[%sm$d\e[0m " ${color% *}
 
-  f="$data_dir/derived/$d"
+  f="$data_dir/derived/${backend}_$d"
 
-  [ -f "$f" ] || jq -Mr ".hourly.data[] | .$d" "$data_dir/src" > "$f"
+  [ -f "$f" ] || jq -Mr "map(.$d)" "$data_dir/norm" > "$f"
 
   plot_data="-c${color#* } -i $f $plot_data"
   i=$((i+1))
